# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterScribe
                                 A QGIS plugin
 This plugin traces the underlying raster map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-11-09
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Mikhail Kondratyev
        email                : mkondratyev85@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import math
import os.path

from qgis.core import Qgis
from qgis.PyQt.QtCore import (
    QCoreApplication,
    QEvent,
    QObject,
    QSettings,
    QSignalBlocker,
    Qt,
    QTranslator,
)
from qgis.PyQt.QtGui import QColor, QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from . import resources  # noqa: F401 - Registers the plugin's Qt resources.
from .pointtool import RasterScribePointTool
from .pointtool_tasks import TraceTaskController

# Import the code for the DockWidget
from .raster_scribe_dockwidget import RasterScribeDockWidget


class LayerTreeShortcutFilter(QObject):
    def __init__(self, pointtool=None):
        super().__init__()
        self.pointtool = pointtool

    def set_pointtool(self, pointtool):
        self.pointtool = pointtool

    def eventFilter(self, obj, event):
        pointtool = self.pointtool
        if (
            pointtool is not None
            and event.type() == QEvent.Type.KeyPress
            and event.modifiers() == Qt.KeyboardModifier.NoModifier
            and pointtool.has_active_trace()
            and event.key() in pointtool.handled_shortcut_keys()
        ):
            pointtool.keyPressEvent(event)
            event.accept()
            return True
        return super().eventFilter(obj, event)


class RasterScribe:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value("locale/userLocale", "en", type=str)[0:2]
        locale_path = os.path.join(self.plugin_dir, "i18n", "{}.qm".format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&Raster Scribe")
        self.toolbar = self.iface.addToolBar("Raster Scribe")
        self.toolbar.setObjectName("RasterScribe")

        self.pluginIsActive = False
        self.dockwidget = None
        self.layer_tree_filter = None
        self.task_controller = TraceTaskController()
        self.tool_identify = None
        self._connections = []
        self._unloaded = False

    def _coerce_spin_box_int(self, candidate_value, spin_box):
        """Return a spin box-friendly integer from persisted settings."""
        default_value = spin_box.value()
        if candidate_value in (None, ""):
            return default_value
        try:
            coerced = int(round(float(candidate_value)))
        except (TypeError, ValueError, OverflowError):
            return default_value
        minimum = spin_box.minimum()
        maximum = spin_box.maximum()
        if maximum >= minimum:
            coerced = max(minimum, min(coerced, maximum))
        return coerced

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("RasterScribe", message)

    def initGui(self):
        """Register the tracing action in the raster menu and plugin toolbar."""
        action = QAction(
            QIcon(":/plugins/raster_scribe/icon.png"),
            self.tr("Raster Scribe"),
            self.iface.mainWindow(),
        )
        action.setObjectName("RasterScribeTrace")
        action.triggered.connect(self.run)
        self.toolbar.addAction(action)
        self.iface.addPluginToRasterMenu(self.menu, action)
        self.actions.append(action)

    # -------------------------------------------------------------------------

    def onClosePlugin(self):
        self._shutdown()

    def _shutdown(self):
        if not self.pluginIsActive:
            return True
        if not self.tool_identify.finish_session():
            return False
        self.pluginIsActive = False
        RasterScribePointTool._disconnect(self._connections)
        if self.layer_tree_filter is not None:
            self.layer_tree_filter.set_pointtool(None)
            self.iface.layerTreeView().removeEventFilter(self.layer_tree_filter)
            self.layer_tree_filter.deleteLater()
            self.layer_tree_filter = None
        tool = self.tool_identify
        if self.map_canvas.mapTool() is tool:
            if self.last_maptool is not None:
                self.map_canvas.setMapTool(self.last_maptool)
            else:
                self.map_canvas.unsetMapTool(tool)
        tool.dispose()
        tool.deleteLater()
        dock, self.dockwidget = self.dockwidget, None
        if dock is not None:
            dock.can_close = None
            dock.hide()
            self.iface.mainWindow().removeDockWidget(dock)
            dock.deleteLater()
        return True

    def unload(self):
        if self._unloaded:
            return
        if not self._shutdown():
            # QGIS unregisters the plugin after any normal return from unload.
            # An exception keeps it registered so the accepted draft can be saved.
            raise RuntimeError(
                "Cannot unload Raster Scribe while its draft could not be saved"
            )
        self.task_controller.shutdown()
        self._unloaded = True
        for action in self.actions:
            self.iface.removePluginRasterMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)
            action.deleteLater()
        self.actions.clear()
        if hasattr(self, "translator"):
            QCoreApplication.removeTranslator(self.translator)
        self.toolbar.deleteLater()

    def activate_map_tool(self):
        current = self.map_canvas.mapTool()
        if current is self.tool_identify:
            return
        if not isinstance(current, RasterScribePointTool):
            self.last_maptool = current
        self.map_canvas.setMapTool(self.tool_identify)

    def _create_interface(self):
        self.dockwidget = RasterScribeDockWidget()
        self.iface.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockwidget)
        self.dockwidget.show()
        self.map_canvas = self.iface.mapCanvas()
        self.last_maptool = None
        self.tool_identify = RasterScribePointTool(
            self.map_canvas,
            self.iface,
            self.turn_off_snap,
            ensure_trace_color_enabled=self.ensure_trace_color_enabled,
            set_trace_color=self.set_trace_color_from_tool,
            scheduler=self.task_controller,
        )
        self.dockwidget.can_close = self.tool_identify.finish_session

    def _read_preferences(self):
        settings, dock = QSettings(), self.dockwidget

        def boolean(key, default):
            value = settings.value(key, default)
            if isinstance(value, bool):
                return value
            if str(value).lower() in ("true", "1"):
                return True
            if str(value).lower() in ("false", "0"):
                return False
            return default

        def color(key, default):
            candidate = settings.value(key, default)
            try:
                value = QColor(candidate)
            except (TypeError, OverflowError):
                value = QColor(default)
            return value if value.isValid() else QColor(default)

        try:
            width = float(settings.value("RasterScribe/preview/width", 2.7))
            if not math.isfinite(width) or width <= 0:
                width = 0.5
        except (TypeError, ValueError, OverflowError):
            width = 0.5
        return {
            "preview": boolean("RasterScribe/preview/enabled", True),
            "preview_color": color("RasterScribe/preview/color", "#FF1493"),
            "width": width,
            "color_enabled": boolean("RasterScribe/color/enabled", False),
            "color": color("RasterScribe/color/value", dock.mColorButton.color()),
            "snap": boolean("RasterScribe/snap/enabled", False),
            "snap_value": self._coerce_spin_box_int(
                settings.value("RasterScribe/snap/tolerance"), dock.mQgsSpinBox
            ),
            "snap2": boolean("RasterScribe/snap2/enabled", False),
            "snap2_value": self._coerce_spin_box_int(
                settings.value("RasterScribe/snap2/tolerance"), dock.SpinBoxSnap
            ),
            "smooth": boolean("RasterScribe/trace/smooth", True),
        }

    def _restore_preferences(self, prefs):
        dock = self.dockwidget
        updates = (
            (dock.checkBoxPreview, "setChecked", prefs["preview"]),
            (dock.previewColorButton, "setColor", prefs["preview_color"]),
            (dock.previewWidthSpinBox, "setValue", prefs["width"]),
            (dock.checkBoxColor, "setChecked", prefs["color_enabled"]),
            (dock.mColorButton, "setColor", prefs["color"]),
            (dock.checkBoxSnap, "setChecked", prefs["snap"]),
            (dock.mQgsSpinBox, "setValue", prefs["snap_value"]),
            (dock.checkBoxSnap2, "setChecked", prefs["snap2"]),
            (dock.SpinBoxSnap, "setValue", prefs["snap2_value"]),
            (dock.checkBoxSmooth, "setChecked", prefs["smooth"]),
        )
        for widget, method, value in updates:
            with QSignalBlocker(widget):
                getattr(widget, method)(value)
        self.checkBoxSnap_changed()
        self.checkBoxSnap2_changed()
        self.checkBoxSmooth_changed()
        self.checkBoxColor_changed()
        self.preview_enabled_changed()
        self.preview_color_changed(dock.previewColorButton.color())
        self.preview_width_changed(dock.previewWidthSpinBox.value())
        dock.SpinBoxSnap.setToolTip(
            self.tr("Vector snap tolerance in canvas CRS map units.")
        )

    def _select_raster(self):
        with QSignalBlocker(self.dockwidget.mMapLayerComboBox):
            self.dockwidget.mMapLayerComboBox.setFilters(Qgis.LayerFilter.RasterLayer)
        self.raster_layer_changed()

    def _connect_interface(self):
        dock = self.dockwidget
        connections = (
            (dock.closingPlugin, self.onClosePlugin),
            (dock.mMapLayerComboBox.layerChanged, self.raster_layer_changed),
            (dock.checkBoxColor.stateChanged, self.checkBoxColor_changed),
            (dock.mColorButton.colorChanged, self.checkBoxColor_changed),
            (dock.checkBoxSnap.stateChanged, self.checkBoxSnap_changed),
            (dock.mQgsSpinBox.valueChanged, self.checkBoxSnap_changed),
            (dock.checkBoxSmooth.stateChanged, self.checkBoxSmooth_changed),
            (dock.checkBoxSnap2.stateChanged, self.checkBoxSnap2_changed),
            (dock.SpinBoxSnap.valueChanged, self.checkBoxSnap2_changed),
            (dock.checkBoxPreview.stateChanged, self.preview_enabled_changed),
            (dock.previewColorButton.colorChanged, self.preview_color_changed),
            (dock.previewWidthSpinBox.valueChanged, self.preview_width_changed),
        )
        for signal, callback in connections:
            signal.connect(callback)
            self._connections.append((signal, callback))
        self.layer_tree_filter = LayerTreeShortcutFilter(self.tool_identify)
        self.iface.layerTreeView().installEventFilter(self.layer_tree_filter)

    def run(self):
        if self._unloaded:
            return
        if self.pluginIsActive:
            self.activate_map_tool()
            return
        self.pluginIsActive = True
        self._create_interface()
        self._restore_preferences(self._read_preferences())
        self._select_raster()
        self._connect_interface()
        self.activate_map_tool()

    def raster_layer_changed(self):
        self.tool_identify.raster_layer_has_changed(
            self.dockwidget.mMapLayerComboBox.currentLayer()
        )
        self.checkBoxColor_changed()

    def checkBoxSmooth_changed(self):
        is_checked = self.dockwidget.checkBoxSmooth.isChecked() is True
        self.tool_identify.smooth_line = is_checked
        settings = QSettings()
        settings.setValue("RasterScribe/trace/smooth", is_checked)

    def checkBoxSnap_changed(self):
        settings = QSettings()
        snap_enabled = self.dockwidget.checkBoxSnap.isChecked()
        try:
            snap_value = int(self.dockwidget.mQgsSpinBox.value())
        except (TypeError, ValueError, OverflowError):
            snap_value = int(self.dockwidget.mQgsSpinBox.minimum())
        settings.setValue("RasterScribe/snap/enabled", snap_enabled)
        settings.setValue("RasterScribe/snap/tolerance", snap_value)

        if snap_enabled:
            self.dockwidget.mQgsSpinBox.setEnabled(True)
            self.tool_identify.snap_tolerance_changed(snap_value)
        else:
            self.dockwidget.mQgsSpinBox.setEnabled(False)
            self.tool_identify.snap_tolerance_changed(None)

    def checkBoxSnap2_changed(self):
        settings = QSettings()
        snap_enabled = self.dockwidget.checkBoxSnap2.isChecked()
        try:
            snap_value = int(self.dockwidget.SpinBoxSnap.value())
        except (TypeError, ValueError, OverflowError):
            snap_value = int(self.dockwidget.SpinBoxSnap.minimum())
        settings.setValue("RasterScribe/snap2/enabled", snap_enabled)
        settings.setValue("RasterScribe/snap2/tolerance", snap_value)

        if snap_enabled:
            self.dockwidget.SpinBoxSnap.setEnabled(True)
            self.tool_identify.snap2_tolerance_changed(snap_value)
        else:
            self.dockwidget.SpinBoxSnap.setEnabled(False)
            self.tool_identify.snap2_tolerance_changed(None)

    def preview_enabled_changed(self):
        enabled = self.dockwidget.checkBoxPreview.isChecked()
        self.dockwidget.previewColorButton.setEnabled(enabled)
        self.dockwidget.previewWidthSpinBox.setEnabled(enabled)
        self.tool_identify.set_preview_enabled(enabled)
        settings = QSettings()
        settings.setValue("RasterScribe/preview/enabled", enabled)

    def preview_color_changed(self, color):
        if not isinstance(color, QColor):
            color = QColor(color)
        self.tool_identify.set_preview_color(color)
        settings = QSettings()
        settings.setValue(
            "RasterScribe/preview/color", color.name(QColor.NameFormat.HexArgb)
        )

    def preview_width_changed(self, value):
        try:
            width = float(value)
        except (TypeError, ValueError, OverflowError):
            width = 0.5
        if not math.isfinite(width) or width <= 0:
            width = 0.5
        self.tool_identify.set_preview_width(width)
        settings = QSettings()
        settings.setValue("RasterScribe/preview/width", width)

    def turn_off_snap(self):
        self.dockwidget.checkBoxSnap.nextCheckState()

    def ensure_trace_color_enabled(self):
        if self.dockwidget is None:
            return

        checkbox = self.dockwidget.checkBoxColor
        if checkbox.isChecked():
            return

        with QSignalBlocker(checkbox):
            checkbox.setChecked(True)

        self.checkBoxColor_changed()

    def set_trace_color_from_tool(self, color):
        if self.dockwidget is None:
            return

        if not isinstance(color, QColor):
            color = QColor(color)

        color_button = self.dockwidget.mColorButton
        with QSignalBlocker(color_button):
            color_button.setColor(color)

        self.checkBoxColor_changed()

    def checkBoxColor_changed(self):
        enabled = self.dockwidget.checkBoxColor.isChecked()
        self.dockwidget.mColorButton.setEnabled(enabled)
        self.dockwidget.checkBoxSnap.setEnabled(enabled)

        color = self.dockwidget.mColorButton.color()
        if not isinstance(color, QColor):
            color = QColor(color)

        self.dockwidget.mQgsSpinBox.setEnabled(
            enabled and self.dockwidget.checkBoxSnap.isChecked()
        )

        settings = QSettings()
        settings.setValue("RasterScribe/color/enabled", enabled)
        if color.isValid():
            settings.setValue(
                "RasterScribe/color/value", color.name(QColor.NameFormat.HexArgb)
            )

        if enabled:
            self.tool_identify.trace_color_changed(color)
        else:
            self.tool_identify.trace_color_changed(False)
