# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterScribe
                                 A QGIS plugin
 This plugin traces the underlying raster map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-11-09
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Mikhail Kondratyev
        email                : mkondratyev85@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import math
import os.path

from qgis.core import (
    Qgis,
    QgsFields,
    QgsMemoryProviderUtils,
    QgsProject,
    QgsRasterLayer,
    QgsVectorLayer,
)
from qgis.PyQt.QtCore import (
    QCoreApplication,
    QEvent,
    QObject,
    QSettings,
    QSignalBlocker,
    Qt,
    QTranslator,
)
from qgis.PyQt.QtGui import QColor, QIcon
from qgis.PyQt.QtWidgets import QAction, QApplication

# Initialize Qt resources from file resources.py
from . import resources  # noqa: F401 - Registers the plugin's Qt resources.
from .attribute_form import show_finished_feature_form
from .pointtool import RasterScribePointTool
from .pointtool_tasks import TraceTaskController

# Import the code for the DockWidget
from .raster_scribe_dockwidget import RasterScribeDockWidget
from .shortcuts import ShortcutSettings, modifier_label


class TracingShortcutFilter(QObject):
    def __init__(self, pointtool=None, require_trace=False):
        super().__init__()
        self.pointtool = pointtool
        self.require_trace = require_trace

    def set_pointtool(self, pointtool):
        self.pointtool = pointtool

    def eventFilter(self, obj, event):
        if event.type() != QEvent.Type.KeyPress:
            return super().eventFilter(obj, event)
        pointtool = self.pointtool
        focus = QApplication.focusWidget()
        # Ignored keys in an inline layer-name editor or canvas input can bubble
        # to its parent. They still belong to that input, not to the trace.
        editing_child = (
            focus is not None
            and focus not in (obj, obj.viewport())
            and obj.isAncestorOf(focus)
        )
        if (
            pointtool is not None
            and not pointtool.disposed
            and not pointtool.suspended
            and (not self.require_trace or pointtool.has_active_trace())
            and pointtool.shortcuts.action(event, include_repeats=True) is not None
        ):
            if not editing_child:
                pointtool.keyPressEvent(event)
            event.accept()
            return True
        return super().eventFilter(obj, event)


class RasterScribe:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value("locale/userLocale", "en", type=str)[0:2]
        locale_path = os.path.join(self.plugin_dir, "i18n", "{}.qm".format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&Raster Scribe")
        self.toolbar = self.iface.addToolBar("Raster Scribe")
        self.toolbar.setObjectName("RasterScribe")

        self.pluginIsActive = False
        self.dockwidget = None
        self.layer_tree_filter = None
        self.canvas_shortcut_filter = None
        self.task_controller = TraceTaskController()
        self.tool_identify = None
        self._connections = []
        self._scratch_connections = []
        self._start_layer_connections = []
        self._unloaded = False

    def _coerce_spin_box_int(self, candidate_value, spin_box):
        """Return a spin box-friendly integer from persisted settings."""
        default_value = spin_box.value()
        if candidate_value in (None, ""):
            return default_value
        try:
            coerced = int(round(float(candidate_value)))
        except (TypeError, ValueError, OverflowError):
            return default_value
        minimum = spin_box.minimum()
        maximum = spin_box.maximum()
        if maximum >= minimum:
            coerced = max(minimum, min(coerced, maximum))
        return coerced

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("RasterScribe", message)

    def initGui(self):
        """Register the tracing action in the raster menu and plugin toolbar."""
        action = QAction(
            QIcon(":/plugins/raster_scribe/icon.png"),
            self.tr("Raster Scribe"),
            self.iface.mainWindow(),
        )
        action.setObjectName("RasterScribeTrace")
        action.triggered.connect(self.run)
        self.toolbar.addAction(action)
        self.iface.addPluginToRasterMenu(self.menu, action)
        self.actions.append(action)

    # -------------------------------------------------------------------------

    def onClosePlugin(self):
        self._shutdown()

    def _shutdown(self):
        if not self.pluginIsActive:
            return True
        if not self.tool_identify.finish_session():
            return False
        self.pluginIsActive = False
        RasterScribePointTool._disconnect(self._connections)
        RasterScribePointTool._disconnect(self._scratch_connections)
        RasterScribePointTool._disconnect(self._start_layer_connections)
        if self.layer_tree_filter is not None:
            self.layer_tree_filter.set_pointtool(None)
            self.iface.layerTreeView().removeEventFilter(self.layer_tree_filter)
            self.layer_tree_filter.deleteLater()
            self.layer_tree_filter = None
        if self.canvas_shortcut_filter is not None:
            self.canvas_shortcut_filter.set_pointtool(None)
            self.map_canvas.removeEventFilter(self.canvas_shortcut_filter)
            self.canvas_shortcut_filter.deleteLater()
            self.canvas_shortcut_filter = None
        tool = self.tool_identify
        if self.map_canvas.mapTool() is tool:
            if self.last_maptool is not None:
                self.map_canvas.setMapTool(self.last_maptool)
            else:
                self.map_canvas.unsetMapTool(tool)
        tool.dispose()
        tool.deleteLater()
        dock, self.dockwidget = self.dockwidget, None
        if dock is not None:
            dock.can_close = None
            dock.hide()
            self.iface.mainWindow().removeDockWidget(dock)
            dock.deleteLater()
        return True

    def unload(self):
        if self._unloaded:
            return
        if not self._shutdown():
            # QGIS unregisters the plugin after any normal return from unload.
            # An exception keeps it registered so the accepted draft can be saved.
            raise RuntimeError(
                "Cannot unload Raster Scribe while its draft could not be saved"
            )
        self.task_controller.shutdown()
        self._unloaded = True
        for action in self.actions:
            self.iface.removePluginRasterMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)
            action.deleteLater()
        self.actions.clear()
        if hasattr(self, "translator"):
            QCoreApplication.removeTranslator(self.translator)
        self.toolbar.deleteLater()

    def activate_map_tool(self):
        current = self.map_canvas.mapTool()
        if current is self.tool_identify:
            return
        if not isinstance(current, RasterScribePointTool):
            self.last_maptool = current
        self.map_canvas.setMapTool(self.tool_identify)

    def _create_interface(self):
        self.shortcuts = ShortcutSettings()
        self.dockwidget = RasterScribeDockWidget(
            shortcuts=self.shortcuts, main_window=self.iface.mainWindow()
        )
        self.iface.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockwidget)
        self.dockwidget.show()
        self.map_canvas = self.iface.mapCanvas()
        self.last_maptool = None
        self.tool_identify = RasterScribePointTool(
            self.map_canvas,
            self.iface,
            self.turn_off_snap,
            ensure_trace_color_enabled=self.ensure_trace_color_enabled,
            set_trace_color=self.set_trace_color_from_tool,
            scheduler=self.task_controller,
            shortcuts=self.shortcuts,
        )
        self.dockwidget.can_close = self.tool_identify.finish_session

    def _read_preferences(self):
        settings, dock = QSettings(), self.dockwidget

        def boolean(key, default):
            value = settings.value(key, default)
            if isinstance(value, bool):
                return value
            if str(value).lower() in ("true", "1"):
                return True
            if str(value).lower() in ("false", "0"):
                return False
            return default

        def color(key, default):
            candidate = settings.value(key, default)
            try:
                value = QColor(candidate)
            except (TypeError, OverflowError):
                value = QColor(default)
            return value if value.isValid() else QColor(default)

        try:
            width = float(settings.value("RasterScribe/preview/width", 2.7))
            if not math.isfinite(width) or width <= 0:
                width = 0.5
        except (TypeError, ValueError, OverflowError):
            width = 0.5
        return {
            "preview": boolean("RasterScribe/preview/enabled", True),
            "preview_color": color("RasterScribe/preview/color", "#FF1493"),
            "width": width,
            "color_enabled": boolean("RasterScribe/color/enabled", False),
            "color": color("RasterScribe/color/value", dock.mColorButton.color()),
            "snap": boolean("RasterScribe/snap/enabled", False),
            "snap_value": self._coerce_spin_box_int(
                settings.value("RasterScribe/snap/tolerance"), dock.mQgsSpinBox
            ),
            "snap2": boolean("RasterScribe/snap2/enabled", False),
            "snap2_value": self._coerce_spin_box_int(
                settings.value("RasterScribe/snap2/tolerance"), dock.SpinBoxSnap
            ),
            "smooth": boolean("RasterScribe/trace/smooth", True),
            "open_attributes": boolean(
                "RasterScribe/attributes/open_after_finish", False
            ),
        }

    def _restore_preferences(self, prefs):
        dock = self.dockwidget
        updates = (
            (dock.checkBoxPreview, "setChecked", prefs["preview"]),
            (dock.previewColorButton, "setColor", prefs["preview_color"]),
            (dock.previewWidthSpinBox, "setValue", prefs["width"]),
            (dock.checkBoxColor, "setChecked", prefs["color_enabled"]),
            (dock.mColorButton, "setColor", prefs["color"]),
            (dock.checkBoxSnap, "setChecked", prefs["snap"]),
            (dock.mQgsSpinBox, "setValue", prefs["snap_value"]),
            (dock.checkBoxSnap2, "setChecked", prefs["snap2"]),
            (dock.SpinBoxSnap, "setValue", prefs["snap2_value"]),
            (dock.checkBoxSmooth, "setChecked", prefs["smooth"]),
            (dock.checkBoxOpenAttributes, "setChecked", prefs["open_attributes"]),
        )
        for widget, method, value in updates:
            with QSignalBlocker(widget):
                getattr(widget, method)(value)
        self.checkBoxSnap_changed()
        self.checkBoxSnap2_changed()
        self.checkBoxSmooth_changed()
        self.checkBoxColor_changed()
        self.open_attributes_changed()
        self.preview_enabled_changed()
        self.preview_color_changed(dock.previewColorButton.color())
        self.preview_width_changed(dock.previewWidthSpinBox.value())
        dock.SpinBoxSnap.setToolTip(
            self.tr("Vector snap tolerance in canvas CRS map units.")
        )

    def _select_raster(self):
        with QSignalBlocker(self.dockwidget.mMapLayerComboBox):
            self.dockwidget.mMapLayerComboBox.setFilters(Qgis.LayerFilter.RasterLayer)
        self.raster_layer_changed()

    def _connect_interface(self):
        dock = self.dockwidget
        connections = (
            (dock.closingPlugin, self.onClosePlugin),
            (dock.mMapLayerComboBox.layerChanged, self.raster_layer_changed),
            (dock.checkBoxColor.stateChanged, self.checkBoxColor_changed),
            (dock.mColorButton.colorChanged, self.checkBoxColor_changed),
            (dock.checkBoxSnap.stateChanged, self.checkBoxSnap_changed),
            (dock.mQgsSpinBox.valueChanged, self.checkBoxSnap_changed),
            (dock.checkBoxSmooth.stateChanged, self.checkBoxSmooth_changed),
            (dock.checkBoxSnap2.stateChanged, self.checkBoxSnap2_changed),
            (dock.SpinBoxSnap.valueChanged, self.checkBoxSnap2_changed),
            (dock.checkBoxPreview.stateChanged, self.preview_enabled_changed),
            (dock.previewColorButton.colorChanged, self.preview_color_changed),
            (dock.previewWidthSpinBox.valueChanged, self.preview_width_changed),
            (dock.checkBoxOpenAttributes.toggled, self.open_attributes_changed),
            (dock.createScratchLayerButton.clicked, self.create_scratch_layer),
            (dock.startTracingButton.clicked, self.start_tracing),
            (self.shortcuts.changed, self.shortcuts_changed),
            (self.tool_identify.attributes_requested, self.open_finished_attributes),
            (self.tool_identify.activated, self.update_start_button),
            (self.iface.layerTreeView().currentLayerChanged, self.start_target_changed),
        )
        for signal, callback in connections:
            signal.connect(callback)
            self._connections.append((signal, callback))
        self.layer_tree_filter = TracingShortcutFilter(
            self.tool_identify, require_trace=True
        )
        self.iface.layerTreeView().installEventFilter(self.layer_tree_filter)
        self.canvas_shortcut_filter = TracingShortcutFilter(self.tool_identify)
        self.map_canvas.installEventFilter(self.canvas_shortcut_filter)
        self.start_target_changed()
        self.shortcuts_changed()

    def shortcuts_changed(self):
        tooltip = self.tr("Open the finished line's form after right-clicking.")
        if self.shortcuts.finish_modifier != "None":
            tooltip += " " + self.tr(
                "{}+right-click reverses this setting for one line."
            ).format(modifier_label(self.shortcuts.finish_modifier))
        self.dockwidget.checkBoxOpenAttributes.setToolTip(tooltip)

    def run(self):
        if self._unloaded:
            return
        if self.pluginIsActive:
            self.activate_map_tool()
            return
        self.pluginIsActive = True
        self._create_interface()
        self._restore_preferences(self._read_preferences())
        self._select_raster()
        self._connect_interface()
        self.activate_map_tool()

    def raster_layer_changed(self):
        RasterScribePointTool._disconnect(self._scratch_connections)
        raster = self.dockwidget.mMapLayerComboBox.currentLayer()
        self.tool_identify.raster_layer_has_changed(raster)
        if raster is not None:
            for signal in ("crsChanged", "isValidChanged", "dataChanged"):
                RasterScribePointTool._connect(
                    raster,
                    signal,
                    self.update_scratch_button,
                    self._scratch_connections,
                )
        self.update_scratch_button()
        self.checkBoxColor_changed()

    def start_target_changed(self, *args):
        RasterScribePointTool._disconnect(self._start_layer_connections)
        layer = self.iface.activeLayer()
        if isinstance(layer, QgsVectorLayer):
            for signal in (
                "editingStarted",
                "editingStopped",
                "isValidChanged",
                "dataSourceChanged",
            ):
                RasterScribePointTool._connect(
                    layer,
                    signal,
                    self.update_start_button,
                    self._start_layer_connections,
                )
        self.update_start_button()

    def tracing_unavailable_reason(self):
        raster = self.dockwidget.mMapLayerComboBox.currentLayer()
        if (
            not isinstance(raster, QgsRasterLayer)
            or not raster.isValid()
            or raster is not self.tool_identify.rlayer
            or self.tool_identify.raster_context.raster_sampler is None
        ):
            return self.tr("Choose a supported RGB raster under Layer to trace.")
        layer = self.tool_identify.get_current_vector_layer()
        if layer is None:
            return self.tr(
                "Select a MultiLineString or MultiCurve layer in the Layers panel."
            )
        if not layer.isEditable():
            return self.tr("Enable editing on the selected line layer.")
        if (
            not layer.dataProvider().capabilities()
            & Qgis.VectorProviderCapability.AddFeatures
        ):
            return self.tr("The selected line layer does not support adding features.")
        return ""

    def update_start_button(self, *args):
        reason = self.tracing_unavailable_reason()
        button = self.dockwidget.startTracingButton
        button.setEnabled(not reason)
        button.setToolTip(
            reason or self.tr("Activate raster tracing on the selected line layer.")
        )

    def start_tracing(self):
        self.update_start_button()
        if not self.dockwidget.startTracingButton.isEnabled():
            return
        self.activate_map_tool()
        self.map_canvas.setFocus(Qt.FocusReason.OtherFocusReason)

    def open_attributes_changed(self):
        enabled = self.dockwidget.checkBoxOpenAttributes.isChecked()
        self.tool_identify.open_attributes_on_finish = enabled
        QSettings().setValue("RasterScribe/attributes/open_after_finish", enabled)

    def open_finished_attributes(self, layer, feature_id):
        try:
            show_finished_feature_form(self.iface, layer, feature_id)
        except Exception as error:
            self.iface.messageBar().pushMessage(
                self.tr("Raster Scribe"),
                self.tr(
                    "The line was created, but its attribute form could not open: {}"
                ).format(error),
                level=Qgis.MessageLevel.Warning,
            )
        finally:
            if self.pluginIsActive and self.map_canvas.mapTool() is self.tool_identify:
                self.map_canvas.setFocus(Qt.FocusReason.OtherFocusReason)

    def _scratch_raster(self):
        raster = self.dockwidget.mMapLayerComboBox.currentLayer()
        if (
            isinstance(raster, QgsRasterLayer)
            and raster.isValid()
            and raster.crs().isValid()
            and self.tool_identify.rlayer is raster
            and self.tool_identify.raster_context.raster_sampler is not None
        ):
            return raster
        return None

    def update_scratch_button(self, *args):
        button = self.dockwidget.createScratchLayerButton
        enabled = self._scratch_raster() is not None
        button.setEnabled(enabled)
        button.setToolTip(
            self.tr(
                "Create an editable temporary line layer using the selected raster's "
                "CRS. Use Make Permanent in QGIS to save it to disk."
            )
            if enabled
            else self.tr("Select a valid RGB raster with a defined CRS first.")
        )
        self.update_start_button()

    def create_scratch_layer(self):
        raster = self._scratch_raster()
        if raster is None or not self.tool_identify.finish_session():
            return None
        project = QgsProject.instance()
        base_name = self.tr("{} — traces").format(raster.name())
        name, suffix = base_name, 2
        while project.mapLayersByName(name):
            name = "{} ({})".format(base_name, suffix)
            suffix += 1
        layer = QgsMemoryProviderUtils.createMemoryLayer(
            name, QgsFields(), Qgis.WkbType.MultiLineString, raster.crs()
        )
        if layer is None or not layer.isValid() or not layer.startEditing():
            if layer is not None:
                layer.deleteLater()
            self.iface.messageBar().pushMessage(
                self.tr("Raster Scribe"),
                self.tr("Could not create an editable scratch layer."),
                level=Qgis.MessageLevel.Warning,
            )
            return None
        project.addMapLayer(layer)
        self.iface.setActiveLayer(layer)
        self.activate_map_tool()
        self.map_canvas.setFocus(Qt.FocusReason.OtherFocusReason)
        self.iface.messageBar().pushMessage(
            self.tr("Raster Scribe"),
            self.tr(
                "Created a temporary scratch layer. Use Make Permanent in the "
                "layer's menu to save it to disk."
            ),
            level=Qgis.MessageLevel.Info,
        )
        return layer

    def checkBoxSmooth_changed(self):
        is_checked = self.dockwidget.checkBoxSmooth.isChecked() is True
        self.tool_identify.smooth_line = is_checked
        settings = QSettings()
        settings.setValue("RasterScribe/trace/smooth", is_checked)

    def checkBoxSnap_changed(self):
        settings = QSettings()
        snap_enabled = self.dockwidget.checkBoxSnap.isChecked()
        try:
            snap_value = int(self.dockwidget.mQgsSpinBox.value())
        except (TypeError, ValueError, OverflowError):
            snap_value = int(self.dockwidget.mQgsSpinBox.minimum())
        settings.setValue("RasterScribe/snap/enabled", snap_enabled)
        settings.setValue("RasterScribe/snap/tolerance", snap_value)

        if snap_enabled:
            self.dockwidget.mQgsSpinBox.setEnabled(True)
            self.tool_identify.snap_tolerance_changed(snap_value)
        else:
            self.dockwidget.mQgsSpinBox.setEnabled(False)
            self.tool_identify.snap_tolerance_changed(None)

    def checkBoxSnap2_changed(self):
        settings = QSettings()
        snap_enabled = self.dockwidget.checkBoxSnap2.isChecked()
        try:
            snap_value = int(self.dockwidget.SpinBoxSnap.value())
        except (TypeError, ValueError, OverflowError):
            snap_value = int(self.dockwidget.SpinBoxSnap.minimum())
        settings.setValue("RasterScribe/snap2/enabled", snap_enabled)
        settings.setValue("RasterScribe/snap2/tolerance", snap_value)

        if snap_enabled:
            self.dockwidget.SpinBoxSnap.setEnabled(True)
            self.tool_identify.snap2_tolerance_changed(snap_value)
        else:
            self.dockwidget.SpinBoxSnap.setEnabled(False)
            self.tool_identify.snap2_tolerance_changed(None)

    def preview_enabled_changed(self):
        enabled = self.dockwidget.checkBoxPreview.isChecked()
        self.dockwidget.previewColorButton.setEnabled(enabled)
        self.dockwidget.previewWidthSpinBox.setEnabled(enabled)
        self.tool_identify.set_preview_enabled(enabled)
        settings = QSettings()
        settings.setValue("RasterScribe/preview/enabled", enabled)

    def preview_color_changed(self, color):
        if not isinstance(color, QColor):
            color = QColor(color)
        self.tool_identify.set_preview_color(color)
        settings = QSettings()
        settings.setValue(
            "RasterScribe/preview/color", color.name(QColor.NameFormat.HexArgb)
        )

    def preview_width_changed(self, value):
        try:
            width = float(value)
        except (TypeError, ValueError, OverflowError):
            width = 0.5
        if not math.isfinite(width) or width <= 0:
            width = 0.5
        self.tool_identify.set_preview_width(width)
        settings = QSettings()
        settings.setValue("RasterScribe/preview/width", width)

    def turn_off_snap(self):
        self.dockwidget.checkBoxSnap.nextCheckState()

    def ensure_trace_color_enabled(self):
        if self.dockwidget is None:
            return

        checkbox = self.dockwidget.checkBoxColor
        if checkbox.isChecked():
            return

        with QSignalBlocker(checkbox):
            checkbox.setChecked(True)

        self.checkBoxColor_changed()

    def set_trace_color_from_tool(self, color):
        if self.dockwidget is None:
            return

        if not isinstance(color, QColor):
            color = QColor(color)

        color_button = self.dockwidget.mColorButton
        with QSignalBlocker(color_button):
            color_button.setColor(color)

        self.checkBoxColor_changed()

    def checkBoxColor_changed(self):
        enabled = self.dockwidget.checkBoxColor.isChecked()
        self.dockwidget.mColorButton.setEnabled(enabled)
        self.dockwidget.checkBoxSnap.setEnabled(enabled)

        color = self.dockwidget.mColorButton.color()
        if not isinstance(color, QColor):
            color = QColor(color)

        self.dockwidget.mQgsSpinBox.setEnabled(
            enabled and self.dockwidget.checkBoxSnap.isChecked()
        )

        settings = QSettings()
        settings.setValue("RasterScribe/color/enabled", enabled)
        if color.isValid():
            settings.setValue(
                "RasterScribe/color/value", color.name(QColor.NameFormat.HexArgb)
            )

        if enabled:
            self.tool_identify.trace_color_changed(color)
        else:
            self.tool_identify.trace_color_changed(False)
