# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterScribeDockWidget
                                 A QGIS plugin
 This plugin traces the underlying raster map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-09
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Mikhail Kondratyev
        email                : mkondratyev85@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from .controls import create_controls_dialog

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "raster_scribe_dockwidget_base.ui")
)


class RasterScribeDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(RasterScribeDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.can_close = None
        self.controls_dialog = None
        self.controlsButton.clicked.connect(self.show_controls)

    def show_controls(self):
        """Keep one reference window so it can stay beside the map canvas."""
        if self.controls_dialog is None:
            self.controls_dialog = create_controls_dialog(self)
        self.controls_dialog.show()
        self.controls_dialog.raise_()
        self.controls_dialog.activateWindow()

    def closeEvent(self, event):
        if self.can_close is not None and not self.can_close():
            event.ignore()
            return
        if self.controls_dialog is not None:
            self.controls_dialog.close()
        self.closingPlugin.emit()
        event.accept()
